#! /usr/bin/env python

#
# -*- encoding: utf-8 -*-
#

# Create a symlink of this file in web server cgi-bin.
# - If not a symlink change FSK_INTRA_LOC to point to FSK_INTRA root dir
# Also create a symlink to lektier.db (default: ~/.skoleintra/lektier.db)
# - The symlink name must be <name of this symlinked file>.db, otherways change DB value below.

import os

# Location of sqlite3 database
DB = __file__ + '.db'  # Create a symlink to the real lektier.db in the same dir as this file (for webusage), __file__ is the name of the symlink of lektier (typically located in the webserver)

FSK_INTRA_LOC = os.path.dirname(os.path.realpath(__file__)) + '/..'
# FSK_INTRA_LOC + WEBLIB + WEBLEKTIER_FILE must match location of file, update FSK_INTRA_LOC to root of fskintra
WEBLIB = '/weblib'  # Don't change
WEBLEKTIER_FILE = '/webLektier.py'  # Don't change

import sys
import os.path
if FSK_INTRA_LOC == '.':
    pass
elif not os.path.isfile(FSK_INTRA_LOC + WEBLIB + WEBLEKTIER_FILE):
    sys.stderr.write('Error: FSK_INTRA_LOC must be updated in %s\n' % __file__)
    sys.exit(1)

# Ok, import webLektier and call main(DB)
sys.path.append(FSK_INTRA_LOC + WEBLIB)
import webLektier
webLektier.main(DB)
