#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Create a symlink of this file in web server cgi-bin.
# - If not a symlink change FSK_INTRA_LOC to point to FSK_INTRA root dir
# Also create a symlink to lektier.db (default: ~/.skoleintra/lektier.db)
# - The symlink name must be <name of this symlinked file>.db, otherways change DB value below.

import os
import cgi
import sys

# Location of sqlite3 database
FILE = os.path.splitext(__file__)[0]
DB = FILE + '.db'  # Create a symlink to the real lektier.db in the same dir as this file (for webusage), __file__ is the name of the symlink of lektier (typically located in the webserver)
INI_FILE = __file__ + '.ini'

FSK_INTRA_LOC = os.path.dirname(os.path.realpath(__file__)) + '/..'
# FSK_INTRA_LOC + WEBLIB + WEBLEKTIER_FILE must match location of file, update FSK_INTRA_LOC to root of fskintra
WEBLIB = '/weblib'  # Don't change
WEBLEKTIER_FILE = '/webLektier.py'  # Don't change

if FSK_INTRA_LOC == '.':
    pass
elif not os.path.isfile(FSK_INTRA_LOC + WEBLIB + WEBLEKTIER_FILE):
    sys.stderr.write('Error: FSK_INTRA_LOC must be updated in %s\n' % __file__)
    sys.exit(1)

# Enable debug using webLektier_debug.py if ?debug=1
enable_debug = False
arguments = cgi.FieldStorage()
if ('debug' in arguments) and (arguments['debug'].value == '1'):
    enable_debug = True

# Import webLektier( or webLektier_debug, if param debug=1) and call main(DB)
sys.path.append(FSK_INTRA_LOC + WEBLIB)
if enable_debug:
    import webLektier_debug
    webLektier_debug.main(
        DB, INI_FILE,
        '<h2><font color="red">Debug version</font></h2>Pleace use the normal <a href="%s">LektieWeb</a> instead without debug=1' % __file__)
else:
    import webLektier
    webLektier.main(
        DB, INI_FILE,
        '')
