#! /usr/bin/env python

#
# -*- encoding: utf-8 -*-
#

# Location of sqlite3 database
DB = './lektier.db'  # Create a symlink to the real lektier.db in the same dir as this file (for webusage)

# This file can be copied to web server cgi-bin and used from a webserver.
# Then update FSK_INTRA_LOC to point to absolute path this dir - root of fskintra.

FSK_INTRA_LOC = '/home/benny/git/github.com/bennyslbs/fskintra.work'  # No / at end!
# FSK_INTRA_LOC + WEBLIB + WEBLEKTIER_FILE must match location of file, update FSK_INTRA_LOC to root of fskintra
WEBLIB = '/weblib'  # Don't change
WEBLEKTIER_FILE = '/webLektier.py'  # Don't change

import sys
import os.path
if FSK_INTRA_LOC == '.':
    pass
elif not os.path.isfile(FSK_INTRA_LOC + WEBLIB + WEBLEKTIER_FILE):
    sys.stderr.write('Error: FSK_INTRA_LOC must be updated in %s\n' % __file__)
    sys.exit(1)

# Ok, import webLektier and call main(DB)
sys.path.append(FSK_INTRA_LOC + WEBLIB)
import webLektier
webLektier.main(DB)
